<?xml version="1.0" ?>

<robot name="umrobot" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <!-- <xacro:property name="body_color" value="Gazebo/Silver" /> -->

  <xacro:macro name="umrobot_sim">
    <!-- <gazebo reference="base_link">
      <material>${body_color}</material>
      <mu1>0.2</mu1>
      <mu2>0.2</mu2>
      <selfCollide>true</selfCollide>
      <gravity>true</gravity>
    </gazebo> -->

    <gazebo reference="wheel_LF">
      <fdir1>1 0 0</fdir1>
      <mu1>2.0</mu1>
      <mu2>0.2</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      
      <minDepth>0.001</minDepth>
      <!-- <maxVel>1.0</maxVel> -->

      <!-- <selfCollide>true</selfCollide>
      <gravity>true</gravity> -->
    </gazebo>

    <gazebo reference="wheel_RF">
      <fdir1>1 0 0</fdir1>
      <mu1>2.0</mu1>
      <mu2>0.2</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      
      <minDepth>0.001</minDepth>
      <!-- <maxVel>1.0</maxVel> -->

      <!-- <selfCollide>true</selfCollide>
      <gravity>true</gravity> -->
    </gazebo>

    <gazebo reference="wheel_LB">
      <fdir1>1 0 0</fdir1>
      <mu1>2.0</mu1>
      <mu2>0.2</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      
      <minDepth>0.001</minDepth>
      <!-- <maxVel>1.0</maxVel> -->

      <!-- <selfCollide>true</selfCollide>
      <gravity>true</gravity> -->
    </gazebo>

    <gazebo reference="wheel_RB">
      <fdir1>1 0 0</fdir1>
      <mu1>2.0</mu1>
      <mu2>0.2</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      
      <minDepth>0.001</minDepth>
      <!-- <maxVel>1.0</maxVel> -->

      <!-- <selfCollide>true</selfCollide>
      <gravity>true</gravity> -->
    </gazebo>
  </xacro:macro>

  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>100</updateRate>
      <leftFrontJoint>joint_LF</leftFrontJoint>
      <leftRearJoint>joint_LB</leftRearJoint>
      <rightFrontJoint>joint_RF</rightFrontJoint>
      <rightRearJoint>joint_RB</rightRearJoint>
      <wheelSeparation>${2*wheel_y}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <torque>20</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>wheel_odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <publishOdomTF>true</publishOdomTF>
      <broadcastTF>false</broadcastTF>
    </plugin>
  </gazebo>

</robot>
